{% set name = "securesystemslib" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/securesystemslib-{{ version }}.tar.gz
  sha256: 34fa63e3296a0540b122a13bf51722ecd015be00c1d2ed45b23442e718920e76

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python

test:
  imports:
    - securesystemslib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/secure-systems-lab/securesystemslib
  license: MIT AND CC0-1.0
  license_family: MIT
  description: |
    A library that provides cryptographic and general-purpose routines for Secure Systems Lab projects at NYU
  license_file:
    - LICENSE
    - securesystemslib/_vendor/ed25519/LICENSE
  summary: A library that provides cryptographic and general-purpose routines for Secure Systems Lab projects at NYU
  doc_url: https://github.com/secure-systems-lab/securesystemslib/tree/main/docs
  dev_url: https://github.com/secure-systems-lab/securesystemslib

extra:
  recipe-maintainers:
    - kenodegard
